@extends('layouts.app')
@section('title', 'SICAM | Asignaciones')
@section('content')
<div class="mx-auto max-w-[1440px] space-y-5 p-4 sm:p-6 lg:p-8">
<header class="flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-bold">Asignaciones</h1><p class="mt-1 text-sm text-muted">Resguardos por persona y área</p></div><a data-crud class="action-button action-button-primary" href="{{ route('patrimonio.asignaciones.create') }}">Nueva asignación</a></header>
<form method="GET" class="form-card flex flex-wrap gap-3"><label class="min-w-0 flex-1"><span class="sr-only">Buscar bien</span><input name="buscar" value="{{ request('buscar') }}" class="form-control" placeholder="Buscar por bien o folio"></label><select name="estado" aria-label="Estado" class="form-control w-auto"><option value="">Todos</option><option value="vigente" @selected(request('estado') === 'vigente')>Vigentes</option><option value="cerrada" @selected(request('estado') === 'cerrada')>Cerradas</option></select><button class="action-button">Filtrar</button></form>
<section class="form-card" data-tour="Consulta resguardos vigentes y anteriores. Reasignar cierra el resguardo actual y crea uno nuevo." data-tour-title="Resguardos"><div class="overflow-x-auto"><table class="data-table w-full min-w-[850px]"><thead><tr><th>Bien</th><th>Tipo</th><th>Responsable</th><th>Dependencia / Área</th><th>Inicio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@forelse($asignaciones as $a)<tr><td>{{ $a->bien?->folio_sicam }}<br>{{ $a->bien?->nombre }}</td><td>{{ $a->tipo_responsabilidad }}</td><td>{{ $a->responsable?->nombre_completo ?? 'Área' }}</td><td>{{ $a->dependencia_id_accesos }} / {{ $a->area_id_accesos }}</td><td>{{ $a->fecha_inicio->format('d/m/Y H:i') }}</td><td>{{ $a->fecha_fin ? 'Cerrada' : 'Vigente' }}</td><td><div class="flex gap-3"><a data-crud href="{{ route('patrimonio.asignaciones.show', $a) }}" class="text-brand" title="Ver asignación">@include('patrimonio.includes.action-icon', ['icon' => 'view', 'label' => 'Ver asignación'])</a>@unless($a->fecha_fin)<a data-crud href="{{ route('patrimonio.asignaciones.edit', $a) }}" class="text-brand" title="Reasignar">@include('patrimonio.includes.action-icon', ['icon' => 'edit', 'label' => 'Reasignar'])</a><form method="POST" action="{{ route('patrimonio.asignaciones.destroy', $a) }}" data-confirm="Se finalizará el resguardo y el bien quedará disponible.">@csrf @method('DELETE')<button class="text-red-700" title="Finalizar asignación">@include('patrimonio.includes.action-icon', ['icon' => 'delete', 'label' => 'Finalizar asignación'])</button></form>@endunless</div></td></tr>@empty<tr><td colspan="7">Sin asignaciones.</td></tr>@endforelse</tbody></table></div>{{ $asignaciones->links() }}</section>
</div>
@endsection
