@extends('layouts.app')
@section('title', 'SICAM | Movimientos')
@section('content')
<div class="mx-auto max-w-[1440px] space-y-5 p-4 sm:p-6 lg:p-8">
<header class="flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-bold">Movimientos</h1><p class="mt-1 text-sm text-muted">Historial y seguimiento de bienes patrimoniales</p></div>@can('movimientos.crear')<a data-crud class="action-button action-button-primary" href="{{ route('patrimonio.movimientos.create') }}">Registrar nota</a>@endcan</header><form method="GET" class="form-card flex flex-wrap gap-3"><label class="min-w-0 flex-1"><span class="sr-only">Buscar bien</span><input name="buscar" value="{{ request('buscar') }}" class="form-control" placeholder="Buscar por bien o folio"></label><select name="tipo" aria-label="Tipo de movimiento" class="form-control w-auto"><option value="">Todos los movimientos</option>@foreach($tipos as $tipo)<option @selected(request('tipo') === $tipo)>{{ $tipo }}</option>@endforeach</select><button class="action-button">Filtrar</button></form><section class="form-card" data-tour="Las altas, modificaciones y cambios de resguardo se registran automáticamente. Puedes agregar notas de seguimiento." data-tour-title="Historial"><div class="overflow-x-auto"><table class="data-table w-full min-w-[760px]"><thead><tr><th>Fecha</th><th>Bien</th><th>Tipo</th><th>Observaciones</th><th>Acciones</th></tr></thead><tbody>@forelse($movimientos as $m)<tr><td>{{ $m->created_at->format('d/m/Y H:i') }}</td><td>{{ $m->bien?->folio_sicam }}</td><td>{{ $m->tipo }}</td><td>{{ Str::limit($m->observaciones, 90) }}</td><td><div class="flex gap-3"><a data-crud href="{{ route('patrimonio.movimientos.show', $m) }}" class="text-brand" title="Ver movimiento">@include('patrimonio.includes.action-icon', ['icon' => 'view', 'label' => 'Ver movimiento'])</a>@can('movimientos.editar')<a data-crud href="{{ route('patrimonio.movimientos.edit', $m) }}" class="text-brand" title="Editar movimiento">@include('patrimonio.includes.action-icon', ['icon' => 'edit', 'label' => 'Editar movimiento'])</a>@endcan
@if($m->tipo === 'NOTA')@can('movimientos.eliminar')<form method="POST" action="{{ route('patrimonio.movimientos.destroy', $m) }}">@csrf @method('DELETE')<button class="text-red-700" title="Eliminar movimiento">@include('patrimonio.includes.action-icon', ['icon' => 'delete', 'label' => 'Eliminar movimiento'])</button></form>@endcan
@endif</div></td></tr>@empty<tr><td colspan="5">Sin movimientos.</td></tr>@endforelse</tbody></table></div>{{ $movimientos->links() }}</section>
</div>
@endsection
