@extends('layouts.app')
@section('title', 'SICAM | Responsable')
@section('content')
<div class="mx-auto max-w-[1440px] space-y-5 p-4 sm:p-6 lg:p-8">
<header class="flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-bold">{{ $responsable->nombre_completo }}</h1><p class="mt-1 text-sm text-muted">{{ $responsable->cargo }} · {{ $responsable->activo ? 'Activo' : 'Inactivo' }}</p></div>@can('responsables.editar')<a data-crud class="action-button" href="{{ route('patrimonio.responsables.edit', $responsable) }}">Editar responsable</a>@endcan</header>
<section class="form-card"><h2>Datos del responsable</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2">@foreach(['numero_empleado' => 'Número de empleado', 'dependencia_id_accesos' => 'Dependencia', 'area_id_accesos' => 'Área', 'correo' => 'Correo', 'telefono' => 'Teléfono'] as $key => $label)<div><dt class="text-xs text-muted">{{ $label }}</dt><dd class="mt-1 text-sm">{{ $responsable->$key ?: 'No registrado' }}</dd></div>@endforeach</dl></section>
<section class="form-card"><h2>Historial de resguardos</h2><div class="mt-4 overflow-x-auto"><table class="data-table w-full min-w-[650px]"><thead><tr><th>Bien</th><th>Inicio</th><th>Fin</th><th>Acción</th></tr></thead><tbody>@forelse($asignaciones as $asignacion)<tr><td>{{ $asignacion->bien?->folio_sicam }} · {{ $asignacion->bien?->nombre }}</td><td>{{ $asignacion->fecha_inicio->format('d/m/Y H:i') }}</td><td>{{ $asignacion->fecha_fin?->format('d/m/Y H:i') ?? 'Vigente' }}</td><td><a data-crud class="text-brand" href="{{ route('patrimonio.asignaciones.show', $asignacion) }}" title="Ver asignación">@include('patrimonio.includes.action-icon', ['icon' => 'view', 'label' => 'Ver asignación'])</a></td></tr>@empty<tr><td colspan="4">Sin asignaciones.</td></tr>@endforelse</tbody></table></div>{{ $asignaciones->links() }}</section>
</div>
@endsection
